### ISSUE TITLE
Do you have a paper on this?

### ISSUE THREAD

**Issue by ZpWaitingForSunshine** [akrodger/htucker-mpi#1]
a great tool

**Comment by akrodger** [comment]
The appendix of the related paper gives a short explanation of the library.
https://www.sciencedirect.com/science/article/pii/S0021999120301157
The paper uses this library for the purposes of studying iterated truncation affects on smooth initial value problems.
See the References section for a list of related papers, including further detail on hierarchical tensor decomposition software.
